# Generated by Django 4.2.9 on 2024-01-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
