# Generated by Django 4.2.9 on 2024-01-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
